### ISSUE TITLE
Default calendar layout when latest = today

### ISSUE THREAD

**Issue by pevernon** [stephencelis/timeframe#1]
Greetings.  When I set the latest value = "new Date()", it still shows the June calendar on the right side.  It is correctly unselectable, however it probably shouldn't be showing at all.  Also, when I click previous and then back forward, it won't go to the June calendar which is correct.   

Any way to make it so if latest = this month that it will not also show next month as default?

Paul

**Comment by stephencelis** [comment]
Initial date should reflect earliest or latest dates [closed by ab059009e28e062d3cc38842427a5b6f9423faa3].
